kind: Service
apiVersion: v1
metadata:
  name: flask-service
  labels:
    app: flask
spec:  
  ports:
  - name: flask
    port: 5432
    nodePort : 30432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: postgres
    