apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - name: api
    nodePort: 30008
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: flask
  type: NodePort
    